### ISSUE TITLE
Installation Details

### ISSUE THREAD

**Issue by knurgazy** [TeRyZh/Roadside-LiDAR-Vehicle-Detection-and-Tracking-Background-Subtraction#1]
Greetings!

I was wondering, how can I install the repository and test it on my laptop?
Could you please provide installation details if it is possible?

Thanks!

**Comment by TeRyZh** [comment]
A three-step is provided.
https://github.com/TeRyZh/Roadside-LiDAR-Vehicle-Detection-and-Tracking-Background-Subtraction/tree/main/programs
