### ISSUE TITLE
How to run your program?

### ISSUE THREAD

**Issue by zwqnju** [TeRyZh/Roadside-LiDAR-Vehicle-Detection-and-Tracking-Background-Subtraction#2]
Could your provide a pipeline? Thanks.

**Comment by TeRyZh** [comment]
A three-step is provided.  
https://github.com/TeRyZh/Roadside-LiDAR-Vehicle-Detection-and-Tracking-Background-Subtraction/tree/main/programs

**Comment by zwqnju** [comment]
Thanks!
