### ISSUE TITLE
Does this repo only contain background subtraction part?

### ISSUE THREAD

**Issue by zwqnju** [TeRyZh/Roadside-LiDAR-Vehicle-Detection-and-Tracking-Background-Subtraction#3]
![Screenshot from 2022-09-09 17-59-21](https://user-images.githubusercontent.com/7918902/189325141-0f3f6fd2-ed33-4a5e-869a-7bff5f9e6da3.png)

I do not see the steps after background substraction. Where can I find them? Thanks.

**Comment by TeRyZh** [comment]
Other parts of the codes will be released in a couple of months. 
Thanks for asking.
